export const Tags = [
  { name: 'gender', childs: [{ name: 'girl' }, { name: 'boy' }, { name: 'tran' }, { name: 'couple' }] },
  {
    name: 'age',
    childs: [
      { name: 'teens', description: '18-25' },
      { name: 'twinks', description: '18-25' },
      { name: 'twenties', description: '26-34' },
      { name: 'milfs', description: '35-48' },
      { name: 'daddies', description: '35-48' },
      { name: 'mature', description: '49-68' },
      { name: 'grannies', description: '69-108' },
      { name: 'grandpas', description: '69-108' },
    ],
  },
  {
    name: 'ethnicity',
    childs: [
      { name: 'arab' },
      { name: 'asian' },
      { name: 'ebony' },
      { name: 'indian' },
      { name: 'latina' },
      { name: 'white' },
    ],
  },
  {
    name: 'physique',
    childs: [
      { name: 'petite' },
      { name: 'skinny' },
      { name: 'athletic' },
      { name: 'muscular' },
      { name: 'medium' },
      { name: 'chunky' },
      { name: 'curvy' },
      { name: 'bbw' },
      { name: 'big' },
    ],
  },
  {
    name: 'hair',
    childs: [{ name: 'bald' }, { name: 'blonde' }, { name: 'brunette' }, { name: 'redhead' }, { name: 'colorful' }],
  },
  {
    name: 'eyes',
    childs: [{ name: 'brown' }, { name: 'blue' }, { name: 'green' }],
  },
  {
    name: 'orientation',
    childs: [{ name: 'bisexual' }, { name: 'gay' }, { name: 'straight' }, { name: 'lesbian' }],
  },
  {
    name: 'activity',
    childs: [
      { name: 'anal' },
      { name: 'anal-beads' },
      { name: 'anal-plug' },
      { name: 'blowjob' },
      { name: 'bondage' },
      { name: 'cooking' },
      { name: 'cosplay' },
      { name: 'dance' },
      { name: 'deepthroat' },
      { name: 'dildo' },
      { name: 'dirty-talk' },
      { name: 'doggy-style' },
      { name: 'domination' },
      { name: 'fingering' },
      { name: 'fisting' },
      { name: 'foot-fetish' },
      { name: 'fuck-machine' },
      { name: 'group-sex' },
      { name: 'outdoor' },
      { name: 'hardcore' },
      { name: 'masturbation' },
      { name: 'shower' },
      { name: 'yoga' },
      { name: 'topless' },
      { name: 'non-nude' },
      { name: 'play-games' },
      { name: 'penis-ring' },
      { name: 'twerk' },
      { name: 'role-play' },
      { name: 'office' },
      { name: 'sex-toys' },
      { name: 'oil' },
      { name: 'ohmibod' },
      { name: 'gang-bang' },
      { name: 'lovense' },
      { name: 'kiiroo' },
      { name: 'squirt' },
      { name: 'nipple-toys' },
      { name: 'gag' },
      { name: 'creampie' },
      { name: 'titty-fuck' },
      { name: 'striptease' },
      { name: 'smoking' },
      { name: 'vaping' },
      { name: '69-position' },
    ],
  },
  {
    name: 'specifics',
    childs: [
      { name: 'big-cock' },
      { name: 'lesbians' },
      { name: 'interracial' },
      { name: 'piercings' },
      { name: 'pregnant' },
      { name: 'big-ass' },
      { name: 'big-tits' },
      { name: 'hairy' },
      { name: 'tattoos' },
      { name: 'small-tits' },
      { name: 'shaven' },
      { name: 'stockings' },
    ],
  },
  {
    name: 'subculture',
    childs: [
      { name: 'mistress' },
      { name: 'cuckold' },
      { name: 'emo' },
      { name: 'glamour' },
      { name: 'goth' },
      { name: 'hipster' },
      { name: 'romantic' },
      { name: 'housewive' },
      { name: 'swinger' },
      { name: 'bdsm' },
      { name: 'slave' },
      { name: 'student' },
      { name: 'bear' },
    ],
  },
];
